# docker-compose.yml
version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    # For dev only for now, disable for staging/prod
    env_file:
      - .env
    environment:
      DB_DATABASE: sarge_db
      DB_USER: user
      DB_PASS: pass
      DB_PORT: 5432
      DB_HOST: postgres
      NODE_ENV: local
      PORT: 49828
    ports:
      - '49828:49828'
    command: npm run watch
    volumes:
      - .:/api/
      - /api/node_modules

  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sarge_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
